# Site settings
title: Jota Freitas Jr 
description: Personal page of Jota Freitas Jr
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jota Freitas Jr
user_description: Android/Web/iOS Team Lead at Virtus - Federal Univerity of Campina Grande (UFCG) and Senior Software Engineer at Accenture of Brazil.
user_title: Senior Software Engineer
email: jotajr@jotajr.com
twitter_username: jotajr
github_username: jotajr
fb_username: jotajr
bitbucket_username: jotajr  

# Google-analytics
google-analytics:
  id: "66929443"

exclude: ['package.json', 'src' , 'node_modules']
