
# SEO settings
title: "Jota Freitas Jr"
title2: "" # default: ""
description: "Testing this theme"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jota Freitas Jr"
  job      : "Software Engineer"
  bio      : "Works at Accenture Brazil and Virtus - UFCG - CEEI " 
  thumb    : /images/author.jpg
  email    : jotajr@jotajr.com
  url      : http://jotajr.github.io
  github   : http://github.com/jotajr
  twitter  : http://twitter.com/jotajr
  facebook : https://www.facebook.com/jotajr
  linkedin : http://linkedin.com/in/jotafreitasjr

# social settings
og_locale: "pt-BR"
twitter_card: "summary_large_image"
twitter_site: "@jotajr"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
