# Site settings
title: Jota Freitas Jr 
description: Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jota Freitas Jr
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Senior Software Engineer
email: jotajr@jotajr.com
twitter_username: jotajr
github_username: jotajr
fb_username: jotajr
bitbucket_username: jotajr  

# Google-analytics
google-analytics:
  id: "66929443"

exclude: ['package.json', 'src' , 'node_modules']
