---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "Jota Freitas Jr"
keywords:    "jotajr, jotafreitasjr, Jota Freitas Jr, Jeosafa Junior, ios, android, ufcg"
description: "Just a developer who wanna develop"
source_link: "https://jotajr.github.io"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: 


# ---- Site configuration ----
domain:      'http://jotajr.com'
form_action:  #'//formspree.io/ridermansb@gmail.com'
phone_number: '+55 (83) 98848-19862882'


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  white:      '#f8f8f8'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'
  blackgray:  '#696969'
  
