# Basic site info
title:              "jota freitas jr •••"
description:        "Life Experience, Technology & Research"
keywords:           "heiswayi nrird, personal blog, software engineer, life experience, technology and research"
logo_text:          "Jota Freitas Jr"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                https://jotajr.com.br # main url
baseurl:            null # for gh-pages
enforce_ssl:        jotajr.com.br

# Site author info
author:
  name:             "Jota Freitas Jr"
  email:            jotafreitasjr@gmail.com
  github_username:  jotajr
  twitter_username: jotajr
  facebook_url:     https://www.facebook.com/jotajr

# Disqus comment settings
disqus_enabled:     true 
disqus_shortname:   hnbloggithub

# GA
google_analytics_code: UA-58296043-7

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           America/Recife 
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
